config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  resources :uploads do
    member do
      get 'download'
    end
  end

  resources :test_drives

  resources :enquiry_forms

  resources :dealer_locations

  resources :features

  resources :passenger_vehicles do
    resources :features
    collection do
      get 'description'
      get 'features'
    end
  end

  resources :about_us

  get 'home/index'
  get 'home/new'

  root to: "home#index"

end

app/models/dealer_location.rb
class DealerLocation < ActiveRecord::Base
  geocoded_by :city  
  after_validation :geocode
end

app/controllers/dealer_locations_controller.rb
class DealerLocationsController < ApplicationController
  before_action :set_dealer_location, only: [:show, :edit, :update, :destroy]

  # GET /dealer_locations
  # GET /dealer_locations.json
  def index
    @dealer_locations = DealerLocation.all
    locations = []
  
        
    gmap_data = Gmaps4rails.build_markers(@dealer_locations) do |location, marker|
      marker.lat  location.latitude
      marker.lng  location.longitude
   
    end
    gon.gmap_data = gmap_data.to_json
    gon.width = "700px"
    gon.height = "700px"
    
  end

  # GET /dealer_locations/1
  # GET /dealer_locations/1.json
  def show
  end

  # GET /dealer_locations/new
  def new
    @dealer_location = DealerLocation.new
  end

  # GET /dealer_locations/1/edit
  def edit
  end

  # POST /dealer_locations
  # POST /dealer_locations.json
  def create
    @dealer_location = DealerLocation.new(dealer_location_params)

    respond_to do |format|
      if @dealer_location.save
        format.html { redirect_to @dealer_location, notice: 'Dealer location was successfully created.' }
        format.json { render :show, status: :created, location: @dealer_location }
      else
        format.html { render :new }
        format.json { render json: @dealer_location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dealer_locations/1
  # PATCH/PUT /dealer_locations/1.json
  def update
    respond_to do |format|
      if @dealer_location.update(dealer_location_params)
        format.html { redirect_to @dealer_location, notice: 'Dealer location was successfully updated.' }
        format.json { render :show, status: :ok, location: @dealer_location }
      else
        format.html { render :edit }
        format.json { render json: @dealer_location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dealer_locations/1
  # DELETE /dealer_locations/1.json
  def destroy
    @dealer_location.destroy
    respond_to do |format|
      format.html { redirect_to dealer_locations_url, notice: 'Dealer location was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dealer_location
      @dealer_location = DealerLocation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dealer_location_params
      params.require(:dealer_location).permit(:country, :name_of_setup, :city, :tel_no, :category, :latitude, :longitude)
    end
end

app/helpers/dealer_locations_helper.rb
module DealerLocationsHelper
end

app/views/dealer_locations/_form.html.haml
= form_for @dealer_location do |f|
  - if @dealer_location.errors.any?
    #error_explanation
      %h2= "#{pluralize(@dealer_location.errors.count, "error")} prohibited this dealer_location from being saved:"
      %ul
        - @dealer_location.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :country
    = f.text_field :country
  .field
    = f.label :name_of_setup
    = f.text_field :name_of_setup
  .field
    = f.label :city
    = f.text_field :city
  .field
    = f.label :tel_no
    = f.text_field :tel_no
  .field
    = f.label :category
    = f.text_field :category
  .field
    = f.label :latitude
    = f.text_field :latitude
  .field
    = f.label :longitude
    = f.text_field :longitude
  .actions
    = f.submit 'Save'

app/views/dealer_locations/edit.html.haml
%h1 Editing dealer_location

= render 'form'

= link_to 'Show', @dealer_location
\|
= link_to 'Back', dealer_locations_path

app/views/dealer_locations/index.html.haml
.row  
  .col-sm-6.col-xs-12
    = render 'shared/map'

%br

//= link_to 'New Dealer location', new_dealer_location_path

app/views/dealer_locations/new.html.haml
%h1 New dealer_location

= render 'form'

= link_to 'Back', dealer_locations_path

app/views/dealer_locations/show.html.haml
%p#notice= notice

%p
  %b Country:
  = @dealer_location.country
%p
  %b Name of setup:
  = @dealer_location.name_of_setup
%p
  %b City:
  = @dealer_location.city
%p
  %b Tel no:
  = @dealer_location.tel_no
%p
  %b Category:
  = @dealer_location.category
%p
  %b Latitude:
  = @dealer_location.latitude
%p
  %b Longitude:
  = @dealer_location.longitude

= link_to 'Edit', edit_dealer_location_path(@dealer_location)
\|
= link_to 'Back', dealer_locations_path