config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  resources :uploads do
    member do
      get 'download'
    end
  end

  resources :test_drives

  resources :enquiry_forms

  resources :dealer_locations

  resources :features

  resources :passenger_vehicles do
    resources :features
    collection do
      get 'description'
      get 'features'
    end
  end

  resources :about_us

  get 'home/index'
  get 'home/new'

  root to: "home#index"

end

app/models/upload.rb
class Upload < ActiveRecord::Base
  mount_uploader :file,  AvatarUploader
  mount_uploader :file_type,  AvatarUploader
  
end

app/controllers/uploads_controller.rb
class UploadsController < ApplicationController
  before_action :set_upload, only: [:show, :edit, :update, :destroy]

  # GET /uploads
  # GET /uploads.json
  def index
    @uploads = Upload.all
  end

  # GET /uploads/1
  # GET /uploads/1.json
  def show
  end

  # GET /uploads/new
  def new
    @upload = Upload.new
  end

  # GET /uploads/1/edit
  def edit
  end

  # POST /uploads
  # POST /uploads.json
  def create
    @upload = Upload.new(upload_params)

    respond_to do |format|
      if @upload.save
        format.html { redirect_to @upload, notice: 'Upload was successfully created.' }
        format.json { render :show, status: :created, location: @upload }
      else
        format.html { render :new }
        format.json { render json: @upload.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /uploads/1
  # PATCH/PUT /uploads/1.json
  def update
    respond_to do |format|
      if @upload.update(upload_params)
        format.html { redirect_to @upload, notice: 'Upload was successfully updated.' }
        format.json { render :show, status: :ok, location: @upload }
      else
        format.html { render :edit }
        format.json { render json: @upload.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /uploads/1
  # DELETE /uploads/1.json
  def destroy
    @upload.destroy
    respond_to do |format|
      format.html { redirect_to uploads_url, notice: 'Upload was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def download
    @upload = Upload.find(params[:id])
    if @upload.file.present?
      send_file "#{Rails.root}/public/"+@upload.file_url
    else
      flash.now[:fail] = I18n.t :fail, :scope => [:upload, :create]
      redirect_to uploads_path
      #render "new"
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_upload
      @upload = Upload.find(params[:id])
    end
    
    # Never trust parameters from the scary internet, only allow the white list through.
    def upload_params
      params.require(:upload).permit(:file_name, :file, :file_type)
    end
end

app/helpers/uploads_helper.rb
module UploadsHelper
end

app/views/uploads/_form.html.haml
= form_for @upload, :multipart =>true, :class => "form-horizontal" do |f|
  .col-sm-8
    .row
      .form-group
        = f.label :file_name,:class => 'col-sm-3 control-label'
        .col-sm-6
          = f.text_field :file_name,:class => 'form-control'
    %br
    .row
      .form-group
        = f.label :image,:class => 'col-sm-3 control-label'
        .col-sm-6
          = f.file_field :file_type,:class => 'form-control'
    %br
    .row
      .form-group
        = f.label :file,:class => 'col-sm-3 control-label'
        .col-sm-6
          = f.file_field :file
    .row
      .col-sm-6.col-sm-offset-5
        = f.submit "submit",:class => 'btn btn-primary'

app/views/uploads/edit.html.haml
%h1 Editing upload

= render 'form'

= link_to 'Show', @upload
\|
= link_to 'Back', uploads_path

app/views/uploads/index.html.haml
%h1 Listing uploads

%table
  %thead
    %tr
      %th Document
     
  %tbody
    - @uploads.each do |upload|
      %tr
        %td
          = image_tag upload.file_type, :size => '200',:class => 'img-thumbnail img-responsive', :width => "100%"
          = upload.file_name
          .pull-right
            = link_to "#{upload.file_name}", download_upload_path(upload)
        

= link_to 'New Upload', new_upload_path

app/views/uploads/new.html.haml
%h1 New upload

= render 'form'

= link_to 'Back', uploads_path

app/views/uploads/show.html.haml
%p#notice= notice

%p
  %b File name:
  = @upload.file_name
%p
  %b File:
  = @upload.file
%p
  %b File type:
  = @upload.file_type

= link_to 'Edit', edit_upload_path(@upload)
\|
= link_to 'Back', uploads_path