config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  resources :uploads do
    member do
      get 'download'
    end
  end

  resources :test_drives

  resources :enquiry_forms

  resources :dealer_locations

  resources :features

  resources :passenger_vehicles do
    resources :features
    collection do
      get 'description'
      get 'features'
    end
  end

  resources :about_us

  get 'home/index'
  get 'home/new'

  root to: "home#index"

end

app/models/passenger_vehicle.rb
class PassengerVehicle < ActiveRecord::Base
  mount_uploader :image, AvatarUploader
  has_many :features
end

app/controllers/passenger_vehicles_controller.rb
class PassengerVehiclesController < ApplicationController
  before_action :set_passenger_vehicle, only: [:show, :edit, :update, :destroy]

  # GET /passenger_vehicles
  # GET /passenger_vehicles.json
  def index
    @passenger_vehicles = PassengerVehicle.all
  end

  def description
    @passenger_vehicles = PassengerVehicle.all
  end

  # GET /passenger_vehicles/1
  # GET /passenger_vehicles/1.json
  def show
  end

  # GET /passenger_vehicles/new
  def new
    @passenger_vehicle = PassengerVehicle.new
  end

  # GET /passenger_vehicles/1/edit
  def edit
  end

  # POST /passenger_vehicles
  # POST /passenger_vehicles.json
  def create
    @passenger_vehicle = PassengerVehicle.new(passenger_vehicle_params)

    respond_to do |format|
      if @passenger_vehicle.save
        format.html { redirect_to @passenger_vehicle, notice: 'Passenger vehicle was successfully created.' }
        format.json { render :show, status: :created, location: @passenger_vehicle }
      else
        format.html { render :new }
        format.json { render json: @passenger_vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /passenger_vehicles/1
  # PATCH/PUT /passenger_vehicles/1.json
  def update
    respond_to do |format|
      if @passenger_vehicle.update(passenger_vehicle_params)
        format.html { redirect_to @passenger_vehicle, notice: 'Passenger vehicle was successfully updated.' }
        format.json { render :show, status: :ok, location: @passenger_vehicle }
      else
        format.html { render :edit }
        format.json { render json: @passenger_vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /passenger_vehicles/1
  # DELETE /passenger_vehicles/1.json
  def destroy
    @passenger_vehicle.destroy
    respond_to do |format|
      format.html { redirect_to passenger_vehicles_url, notice: 'Passenger vehicle was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_passenger_vehicle
      @passenger_vehicle = PassengerVehicle.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def passenger_vehicle_params
      params.require(:passenger_vehicle).permit(:name, :introduction, :image)
    end
end

app/helpers/passenger_vehicles_helper.rb
module PassengerVehiclesHelper
end

app/views/passenger_vehicles/_form.html.haml
= form_for @passenger_vehicle , :html => {:class => "form-horizontal" , :role => "form"} do |f|
  .row
    .col-md-2.col-xs-12
      = f.label :name
    .col-md-6.col-xs-12
      = f.text_field :name
  %br
  .row
    .col-md-2.col-xs-12
      = f.label :introduction
    .col-md-6.col-xs-12
      = f.text_field :introduction
  %br
  .row
    .col-md-2.col-xs-12
      = f.label :image
    .col-md-6.col-xs-12
      = f.file_field :image
  %br
  .row
    %center
      = button_tag "Save", :type => "submit", :class => 'btn btn-primary'

app/views/passenger_vehicles/description.html.haml
- @passenger_vehicles.each do |passenger_vehicle|
  .row
    .col-md-12.col-xs-12
      %center
        = image_tag passenger_vehicle.image, :size => '200',:class => 'img-thumbnail img-responsive', :width => "100%"
  .row
    &nbsp &nbsp &nbsp &nbsp 
    = passenger_vehicle.introduction
  .row
    .pull-right
      = link_to 'Edit', edit_passenger_vehicle_path(passenger_vehicle), :class => "btn btn-primary"
  

app/views/passenger_vehicles/edit.html.haml
= render 'form'

= link_to 'Show', @passenger_vehicle

= link_to 'Back', passenger_vehicles_path

app/views/passenger_vehicles/features.html.haml
.row{:ng_controller => "FeatureController"}
  = link_to "Add Feature" , "#" , :ng_click  => "newFeature()" , :class => "btn btn-primary"
  %table.table.table-bordered
    %thead
      %tr
        %th{:width => "50%"} Feature
        %th Feature Type
        %th 
      %tr{:ng_show => "new_specification"}
        %th
          %input{:type => "text", :ng_model => "new_specification.spec_label", :class => "form-control", :placeholder => "Specification"}
        %th
          %input{:type => "text", :ng_model => "new_specification.spec_value", :class => "form-control", :placeholder => "Specification Value"}
        %th
          = link_to "Save", "#", :ng_click => "saveFeature(new_specification)", :class => "btn btn-primary btn-sm"

app/views/passenger_vehicles/index.html.haml
= link_to 'New Passenger vehicle', new_passenger_vehicle_path

app/views/passenger_vehicles/new.html.haml
%h1 New passenger_vehicle

= render 'form'

= link_to 'Back', passenger_vehicles_path

app/views/passenger_vehicles/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @passenger_vehicle.name
%p
  %b Introduction:
  = @passenger_vehicle.introduction
%p
  %b Image:
  = @passenger_vehicle.image

= link_to 'Edit', edit_passenger_vehicle_path(@passenger_vehicle)
\|
= link_to 'Back', passenger_vehicles_path