config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  resources :uploads do
    member do
      get 'download'
    end
  end

  resources :test_drives

  resources :enquiry_forms

  resources :dealer_locations

  resources :features

  resources :passenger_vehicles do
    resources :features
    collection do
      get 'description'
      get 'features'
    end
  end

  resources :about_us

  get 'home/index'
  get 'home/new'

  root to: "home#index"

end

app/controllers/enquiry_forms_controller.rb
class EnquiryFormsController < ApplicationController
  before_action :set_enquiry_form, only: [:show, :edit, :update, :destroy]

  # GET /enquiry_forms
  # GET /enquiry_forms.json
  def index
    @enquiry_forms = EnquiryForm.all
  end

  # GET /enquiry_forms/1
  # GET /enquiry_forms/1.json
  def show
  end

  # GET /enquiry_forms/new
  def new
    @enquiry_form = EnquiryForm.new
  end

  # GET /enquiry_forms/1/edit
  def edit
  end

  # POST /enquiry_forms
  # POST /enquiry_forms.json
  def create
    @enquiry_form = EnquiryForm.new(enquiry_form_params)

    respond_to do |format|
      if @enquiry_form.save
        format.html { redirect_to @enquiry_form, notice: 'Enquiry form was successfully created.' }
        format.json { render :show, status: :created, location: @enquiry_form }
      else
        format.html { render :new }
        format.json { render json: @enquiry_form.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /enquiry_forms/1
  # PATCH/PUT /enquiry_forms/1.json
  def update
    respond_to do |format|
      if @enquiry_form.update(enquiry_form_params)
        format.html { redirect_to @enquiry_form, notice: 'Enquiry form was successfully updated.' }
        format.json { render :show, status: :ok, location: @enquiry_form }
      else
        format.html { render :edit }
        format.json { render json: @enquiry_form.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /enquiry_forms/1
  # DELETE /enquiry_forms/1.json
  def destroy
    @enquiry_form.destroy
    respond_to do |format|
      format.html { redirect_to enquiry_forms_url, notice: 'Enquiry form was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_enquiry_form
      @enquiry_form = EnquiryForm.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def enquiry_form_params
      params.require(:enquiry_form).permit(:name, :address, :email, :mobile, :city, :zip_code, :vehicle_type, :query)
    end
end

app/helpers/enquiry_forms_helper.rb
module EnquiryFormsHelper
end

app/views/enquiry_forms/_form.html.haml
= form_for @enquiry_form, :html => {:class => "form-horizontal" , :role => "form"} do |f|
  .row
    .col-md-2.col-xs-12
      .pull-left.required
        = f.label :name
    .col-md-3.col-xs-12
      = f.text_field :name , :class => 'form-control'
  %br
  .row
    .col-md-2.col-xs-12
      = f.label :address
    .col-md-3.col-xs-12
      = f.text_area :address , :class => 'form-control'
  %br
  .row
    .col-md-2.col-xs-12
      .pull-left.required
        = f.label :email
    .col-md-3.col-xs-12
      = f.text_field :email , :class => 'form-control'
  %br
  .row
    .col-md-2.col-xs-12
      = f.label :mobile
    .col-md-3.col-xs-12
      = f.text_field :mobile , :class => 'form-control'
  %br
  .row
    .col-md-2.col-xs-12
      = f.label :city
    .col-md-3.col-xs-12
      = f.text_field :city , :class => 'form-control'
  %br
  .row
    .col-md-2.col-xs-12
      = f.label :zip_code
    .col-md-3.col-xs-12
      = f.text_field :zip_code , :class => 'form-control'
  %br
  .row
    .col-md-2.col-xs-12
      .pull-left.required
        = f.label :vehicle_type
    .col-md-3.col-xs-12
      = f.number_field :vehicle_type , :class => 'form-control'
  %br
  .row
    .col-md-2.col-xs-12
      = f.label :query
    .col-md-3.col-xs-12
      = f.text_area :query, :class => 'form-control'
  %br
  .row
    .col-md-2.col-xs-12
    .col-md-1.col-xs-12
      = button_tag 'Submit', :type => 'submit', :class => 'btn btn-default'

app/views/enquiry_forms/edit.html.haml
%h1 Editing enquiry_form

= render 'form'

= link_to 'Show', @enquiry_form
\|
= link_to 'Back', enquiry_forms_path

app/views/enquiry_forms/index.html.haml
%h1 Listing enquiry_forms

%table
  %thead
    %tr
      %th Name
      %th Address
      %th Email
      %th Mobile
      %th City
      %th Zip code
      %th Vehicle type
      %th Query
      %th
      %th
      %th

  %tbody
    - @enquiry_forms.each do |enquiry_form|
      %tr
        %td= enquiry_form.name
        %td= enquiry_form.address
        %td= enquiry_form.email
        %td= enquiry_form.mobile
        %td= enquiry_form.city
        %td= enquiry_form.zip_code
        %td= enquiry_form.vehicle_type
        %td= enquiry_form.query
        %td= link_to 'Show', enquiry_form
        %td= link_to 'Edit', edit_enquiry_form_path(enquiry_form)
        %td= link_to 'Destroy', enquiry_form, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Enquiry form', new_enquiry_form_path

app/views/enquiry_forms/new.html.haml
%h5 
  %b Enquiry Form
%hr
%h3{:style => "color:red"} Fields marked with * are mandatory 
%br
.row
  .col-md-1.col-xs-1
  .col-md-10.col-xs-11
    = render 'form'

app/views/enquiry_forms/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @enquiry_form.name
%p
  %b Address:
  = @enquiry_form.address
%p
  %b Email:
  = @enquiry_form.email
%p
  %b Mobile:
  = @enquiry_form.mobile
%p
  %b City:
  = @enquiry_form.city
%p
  %b Zip code:
  = @enquiry_form.zip_code
%p
  %b Vehicle type:
  = @enquiry_form.vehicle_type
%p
  %b Query:
  = @enquiry_form.query

= link_to 'Edit', edit_enquiry_form_path(@enquiry_form)
\|
= link_to 'Back', enquiry_forms_path